=== Team302/2026Rebuilt/src/main/deploy/auton/auton.dtd
<!ELEMENT auton (snippet | primitive)* >

<!ELEMENT snippet EMPTY>
<!ATTLIST snippet file CDATA #IMPLIED>

<!ELEMENT primitive (zone* ) >
<!ATTLIST primitive 
          id                ( DO_NOTHING | HOLD_POSITION | 
                              TRAJECTORY_DRIVE | RESET_POSITION | RESET_POSITION_NO_VISION | DRIVE_STOP_MECH) "DO_NOTHING"
		  pathUpdateOption 	( NOTHING) "NOTHING"
		  time				CDATA #IMPLIED
		  delayOption		(START ) "START"
          headingOption     CDATA "IGNORE"
          heading           CDATA "0.0"
		  choreoname		CDATA #IMPLIED
		  visionAligment    ( UNKNOWN ) "UNKNOWN"
		  launcherState		( STATE_OFF | STATE_INITIALIZE | STATE_IDLE | STATE_PREPARE_TO_LAUNCH ) "STATE_IDLE"
		  intakeState		( STATE_OFF | STATE_INTAKE | STATE_EXPEL | STATE_LOAD_HOPPER | STATE_FORCE_INTAKE_AUTON ) "STATE_OFF"
		  climberState		( STATE_OFF | STATE_WANT_TO_CLIMB ) "STATE_OFF"
>


<!ELEMENT zone EMPTY >
<!ATTLIST zone
		filename CDATA #REQUIRED
		
>

=== Team302/2026Rebuilt/src/main/deploy/auton/BlueRLaunch0DepOutScoreClimb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "DRIVE_STOP_MECH"/>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightNoneOutpostDepot_A"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLaunchZone.xml"/>
<zone filename = "BlueOutpostZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightNoneOutpostDepot_B"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightNoneOutpostDepot_C"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLaunchZone.xml"/>
<zone filename = "BlueDepotZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH">
<zone filename = "BlueClimbingZone.xml"/>
</primitive>
<!--This path could honestly do a lot more, we could probably grab some pieces from our side if people are willing to pass-->



</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/BlueBDepKeep3DepNOutScoreNCliInvert.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<!-- <primitive id = "DRIVE_STOP_MECH"
time = "0.1"
intakeState = "STATE_OFF">
</primitive> -->

<snippet file = "LeftBumpInit.xml"/>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_A_Var2"
time = "3.0"
intakeState = "STATE_INTAKE">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_C"
time = "5.0">
<zone filename = "BlueLeftBumpZoneRect.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<snippet file = "GoToDepot.xml"/>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_C2"
time = "5.0"
intakeState = "STATE_INTAKE"
launcherState = "STATE_IDLE">
<zone filename = "BlueLeftBumpZoneRect.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_D"
time = "5.0"
intakeState = "STATE_INTAKE">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_F"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLeftBumpZoneRect.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH"
time = "5.0">
</primitive>

</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/Archive/RedTOutLaunch2NDepNOutScoreClimb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightBumpNZNZ_A"
time = "5.0">
<zone filename = "RedRightBumpZone.xml"/>
</primitive>


<primitive id = "TRAJECTORY_DRIVE"
choreoname = "RightToLeftNZ"
time = "5.0">
<zone filename = "RedLeftBumpZone.xml"/>
</primitive>


<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightBumpNZNZ_C"
time = "5.0">
<zone filename = "RedLeftBumpZone.xml"/>
</primitive>


<primitive id = "TRAJECTORY_DRIVE"
choreoname = "LeftToRightNZ"
time = "5.0"/>
<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightBumpNZNZ_E"
time = "5.0">
<zone filename = "RedRightBumpZone.xml"/>
</primitive>


<!--This path could honestly do a lot more, we could probably grab some pieces from our side if people are willing to pass-->



</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/RedMLDrop3NDNOScoreNC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_Init"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLeftBumpZoneRect.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_A"
time = "3.0"
intakeState = "STATE_INTAKE">
<!-- <zone filename = "RedLeftBumpZoneRect.xml"/> -->
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_B"
time = "3.0"
intakeState = "STATE_INTAKE">
</primitive>


<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_C"
time = "5.0">
<zone filename = "RedLeftBumpZoneRect.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH"
time = "5.0">
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_C2"
time = "5.0"
intakeState = "STATE_INTAKE"
launcherState = "STATE_IDLE">
<zone filename = "RedLeftBumpZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_D"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLeftBumpZoneRect.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_E"
time = "3.0"
intakeState = "STATE_INTAKE"
launcherState = "STATE_IDLE">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_F"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLeftBumpZoneRect.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/BlueBDepKeep3NDepNOutScoreNCliWin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<!-- <primitive id = "DRIVE_STOP_MECH"
time = "0.1"
intakeState = "STATE_OFF">
</primitive> -->

<snippet file = "LeftBumpInit.xml"/>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_A"
time = "3.0"
intakeState = "STATE_INTAKE">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_C"
time = "5.0">
<zone filename = "BlueLeftBumpZoneRect.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH"
time = "5.0">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_C2"
time = "5.0"
intakeState = "STATE_INTAKE"
launcherState = "STATE_IDLE">
<zone filename = "BlueLeftBumpZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_D"
time = "5.0"
intakeState = "STATE_INTAKE">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_F"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLeftBumpZoneRect.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH"
time = "5.0">
</primitive>

</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/BlueBOutKeep3NDepNOutScoreNCliWin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<!-- <primitive id = "DRIVE_STOP_MECH"
time = "0.1"
intakeState = "STATE_OFF">
</primitive> -->

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop3_Init"
time = "3.0">
<zone filename = "BlueRightBumpZoneRect.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop3_A"
intakeState = "STATE_INTAKE"
time = "3.0">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop3_C"
time = "5.0">
<zone filename = "BlueRightBumpZone.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH"
launcherState = "STATE_PREPARE_TO_LAUNCH"
time = "10.0">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop3_D"
time = "5.0"
intakeState = "STATE_INTAKE"
launcherState = "STATE_IDLE">
<zone filename = "BlueRightBumpZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop3_E"
time = "5.0"
intakeState = "STATE_INTAKE">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop3_F"
time = "3.0">
<zone filename = "BlueLaunchZone.xml"/>
<zone filename = "BlueRightBumpZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH"
launcherState = "STATE_PREPARE_TO_LAUNCH"
time = "10.0">
</primitive>

</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/BlueMLaunch0DepOutScoreClimb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "DRIVE_STOP_MECH"
launcherState = "STATE_LAUNCH"/>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDepotOutpost_A"
time = "4.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLaunchZone.xml"/>
<zone filename = "BlueDepotZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDepotOutpost_B"
time = "4.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLaunchZone.xml"/>
<zone filename = "BlueOutpostZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDepotOutpost_C"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDepotOutpost_D"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH">
<zone filename = "BlueClimbingZone.xml"/>
</primitive>
<!--This path could honestly do a lot more, we could probably grab some pieces from our side if people are willing to pass-->



</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/RedRLaunch0DepOutScoreClimb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "DRIVE_STOP_MECH"/>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightNoneOutpostDepot_A"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLaunchZone.xml"/>
<zone filename = "RedOutpostZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightNoneOutpostDepot_B"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLaunchZone.xml"/>
<zone filename = "RedDepotZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueRightNoneOutpostDepot_C"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH">
<zone filename = "RedClimbingZone.xml"/>
</primitive>
<!--This path could honestly do a lot more, we could probably grab some pieces from our side if people are willing to pass-->



</auton>
