=== Team302/2026Rebuilt/src/main/deploy/auton/auton.dtd
<!ELEMENT auton (snippet | primitive)* >

<!ELEMENT snippet EMPTY>
<!ATTLIST snippet file CDATA #IMPLIED>

<!ELEMENT primitive (zone* ) >
<!ATTLIST primitive 
          id                ( DO_NOTHING | HOLD_POSITION | 
                              TRAJECTORY_DRIVE | RESET_POSITION | RESET_POSITION_NO_VISION | DRIVE_STOP_MECH) "DO_NOTHING"
		  pathUpdateOption 	( NOTHING) "NOTHING"
		  time				CDATA #IMPLIED
		  delayOption		(START ) "START"
          headingOption     CDATA "IGNORE"
          heading           CDATA "0.0"
		  choreoname		CDATA #IMPLIED
		  visionAligment    ( UNKNOWN ) "UNKNOWN"
		  launcherState		( STATE_OFF | STATE_INITIALIZE | STATE_IDLE | STATE_PREPARE_TO_LAUNCH ) "STATE_IDLE"
		  intakeState		( STATE_OFF | STATE_INTAKE | STATE_EXPEL | STATE_LOAD_HOPPER | STATE_FORCE_INTAKE_AUTON ) "STATE_OFF"
		  climberState		( STATE_OFF | STATE_WANT_TO_CLIMB ) "STATE_OFF"
>


<!ELEMENT zone EMPTY >
<!ATTLIST zone
		filename CDATA #REQUIRED
		
>

=== Team302/2026Rebuilt/src/main/deploy/auton/RedBDepKeep3NDepNOutScoreNCliInvert.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<!-- <primitive id = "DRIVE_STOP_MECH"
time = "0.1"
intakeState = "STATE_OFF">
</primitive> -->

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_Init"
time = "3.0">
<zone filename = "RedLeftBumpZoneRect.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_A_Var2"
time = "3.0"
intakeState = "STATE_INTAKE">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_C"
time = "5.0">
<zone filename = "RedLeftBumpZoneRect.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH"
time = "10.0">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_C2"
time = "5.0"
intakeState = "STATE_INTAKE"
launcherState = "STATE_IDLE">
<zone filename = "RedLeftBumpZoneRect.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_D"
time = "5.0"
intakeState = "STATE_INTAKE">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_F"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLeftBumpZoneRect.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH"
time = "5.0">
</primitive>

</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/BlueMRDrop2NDNOScoreNC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_A"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLeftBumpZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_B"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueRightBumpZone.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_C"
time = "5.0">
<zone filename = "BlueRightBumpZone.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_D"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueRightBumpZone.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_E"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueRightBumpZone.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_F"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueRightBumpZone.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/RedMLDrop2NDNOScoreNC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop2_A"
time = "4.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLeftBumpZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop2_B"
time = "4.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedRightBumpZone.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop2_C"
time = "4.0">
<zone filename = "RedRightBumpZone.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop2_D"
time = "4.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLeftBumpZone.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/BlueTDepLaunch0DepOutScoreClimb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>


<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueLDepotOutpost_A"
time = "4.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLaunchZone.xml"/>
<!-- <zone filename = "BlueDepotZone.xml"/> -->
<!--This is only commented out because I like the swoop, but up to testing-->
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueLDepotOutpost_B"
time = "4.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLaunchZone.xml"/>
<zone filename = "BlueOutpostZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueLDepotOutpost_C"
time = "4.5"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH">
<zone filename = "BlueClimbingZone.xml"/>
</primitive>



</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/RedBDepKeep3DepNOutScoreNCliWin.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<!-- <primitive id = "DRIVE_STOP_MECH"
time = "0.1"
intakeState = "STATE_OFF">
</primitive> -->

<snippet file = "RightBumpInit.xml"/>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_A"
time = "3.0"
intakeState = "STATE_INTAKE">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_C"
time = "5.0">
<zone filename = "RedLeftBumpZoneRect.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<snippet file = "GoToDepot.xml"/>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_C2"
time = "5.0"
intakeState = "STATE_INTAKE"
launcherState = "STATE_IDLE">
<zone filename = "RedLeftBumpZoneRect.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_D"
time = "5.0"
intakeState = "STATE_INTAKE">
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMLDrop3_F"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLeftBumpZoneRect.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "DRIVE_STOP_MECH"
time = "5.0">
</primitive>

</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/RedMRDrop2NDNOScoreNC.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_A"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedRightBumpZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_B"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_C"
time = "5.0">
<zone filename = "RedLeftBumpZone.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_D"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedRightBumpZone.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_E"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueMRDrop2_F"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RedRightBumpZone.xml"/>
<zone filename = "RedLaunchZone.xml"/>
</primitive>

</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/BlueLLaunch2NDNOScoreClimb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>



<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueLeftBumpNZNZ_A"
time = "2.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLeftBumpZone.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "LeftToRightNZ"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueRightBumpZone.xml"/>
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<!-- <primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueLeftBumpNZNZ_C"
time = "1.5"> -->
<!-- 
</primitive> -->

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "RightToLeftNZ"
time = "3.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLeftBumpZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueLeftBumpNZNZ_D"
time = "2.0">
<zone filename = "BlueLaunchZone.xml"/>
</primitive>

<!--This path could honestly do a lot more, we could probably grab some pieces from our side if people are willing to pass-->



</auton>

=== Team302/2026Rebuilt/src/main/deploy/auton/RedTDepLaunch2NDepNOutScoreClimb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE auton SYSTEM "auton.dtd">
<auton>


<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueLeftBumpNZNZ_A"
time = "2.0"
intakeState = "STATE_INTAKE">
<zone filename = "BlueLeftBumpNZNZ_A.xml"/>
</primitive>


<primitive id = "TRAJECTORY_DRIVE"
choreoname = "LeftToRightNZ"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "LeftToRightNZ.xml"/>
</primitive>


<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueLeftBumpNZNZ_C"
time = "5.0">
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<primitive id = "TRAJECTORY_DRIVE"
choreoname = "RightToLeftNZ"
time = "5.0"
intakeState = "STATE_INTAKE">
<zone filename = "RightToLeftNZ.xml"/>
</primitive>


<primitive id = "TRAJECTORY_DRIVE"
choreoname = "BlueLeftBumpNZNZ_D"
time = "5.0">
<zone filename = "RedLaunchZone.xml"/>
</primitive>

<!--This path could honestly do a lot more, we could probably grab some pieces from our side if people are willing to pass-->



</auton>
